"""
Main CLI entry point for Yukta commands.
Provides: init, validate, tool run commands.
"""

import click
import os
import sys
from pathlib import Path
from datetime import datetime
import yaml

from .templates import (
    get_agent_template,
    get_skill_template,
    get_tool_template,
    get_tool_impl_template,
    get_team_template,
    get_config_template,
    get_index_template,
    get_readme_template,
    get_bootstrap_template,
)
from ..ecosystem.validator import (
    validate_agent,
    validate_bootstrap,
    validate_config,
    validate_index,
    validate_skill,
    validate_tool,
    validate_team,
)
from ..api.compiler import compile_ecosystem, generate_index
from ..api.runner import run_tool


@click.group()
@click.version_option(version="2.1.0")
def cli():
    """Yukta - Modular AI Agent Framework"""
    pass


@cli.command("init")
@click.argument("what")
@click.argument("project_name")
def init(what, project_name):
    """Initialize a new ecosystem project
    
    Usage: yukta init ecosystem <project_name>
    """
    if what != "ecosystem":
        click.echo(f"Error: Unknown argument '{what}'. Use 'ecosystem' instead.", err=True)
        sys.exit(1)
    
    project_path = Path(project_name)
    
    if project_path.exists():
        click.echo(f"Error: Directory '{project_name}' already exists", err=True)
        sys.exit(1)
    
    project_path.mkdir(parents=True)

    dirs = [
        "agents",
        "skills",
        "tools",
        "tools-impl",
        "teams",
        "skills-box",
        "config",
        "bootstrap",
    ]

    for d in dirs:
        (project_path / d).mkdir(parents=True, exist_ok=True)

    (project_path / "skills" / "skill-name").mkdir(parents=True, exist_ok=True)
    (project_path / "build").mkdir(parents=True, exist_ok=True)
    
    (project_path / "agents" / "agent.yaml").write_text(get_agent_template(project_name))
    (project_path / "skills" / "skill-name" / "SKILL.md").write_text(get_skill_template(project_name))
    (project_path / "tools" / "tool.yaml").write_text(get_tool_template(project_name))
    (project_path / "tools-impl" / "__init__.py").write_text(
        f"# Tool implementations for {project_name} ecosystem\n# Add your tool functions here\n"
    )
    (project_path / "tools-impl" / "tool_impl.py").write_text(get_tool_impl_template(project_name))
    (project_path / "teams" / "team.yaml").write_text(get_team_template(project_name))
    (project_path / "config" / "main.yaml").write_text(get_config_template(project_name))
    (project_path / "bootstrap" / "using-yukta.yaml").write_text(get_bootstrap_template(project_name))
    (project_path / "skills-box" / "index.yaml").write_text(get_index_template(project_name))
    
    (project_path / "README.md").write_text(get_readme_template(project_name))
    (project_path / "agents" / "README.md").write_text(
        "# Agents\n\nDefine your agent configurations here.\n"
    )
    (project_path / "skills" / "README.md").write_text(
        "# Skills\n\nDefine your skill workflows here.\n"
    )
    (project_path / "tools" / "README.md").write_text(
        "# Tools\n\nDefine your tool descriptors here.\n"
    )
    (project_path / "teams" / "README.md").write_text(
        "# Teams\n\nDefine your team configurations here.\n"
    )
    (project_path / "build" / "README.md").write_text(
        "# Build\n\nThis directory contains compiled ecosystem files.\nAuto-generated by `yukta validate ecosystem`.\n"
    )
    
    click.echo(f"Created ecosystem project: {project_name}/")
    click.echo("\nNext steps:")
    click.echo(f"  1. cd {project_name}")
    click.echo("  2. Edit agents/agent.yaml with your agent config")
    click.echo("  3. Edit skills/skill-name/SKILL.md with your skill workflow")
    click.echo("  4. Edit tools-impl/tool_impl.py for your tools")
    click.echo("  5. Run: yukta validate ecosystem ./")
    click.echo("  6. Start using your ecosystem!")


@cli.command("validate")
@click.argument("what")
@click.argument("path", default=".")
def validate(what, path):
    """Validate an ecosystem project (one-time compilation)
    
    Usage: yukta validate ecosystem <path>
    """
    if what != "ecosystem":
        click.echo(f"Error: Unknown argument '{what}'. Use 'ecosystem' instead.", err=True)
        sys.exit(1)
    
    ecosystem_path = Path(path)
    
    if not ecosystem_path.exists():
        click.echo(f"Error: Path '{path}' does not exist", err=True)
        sys.exit(1)
    
    click.echo(f"Validating ecosystem: {ecosystem_path}...")

    errors = []

    config_dir = ecosystem_path / "config"
    bootstrap_dir = ecosystem_path / "bootstrap"
    skills_box_dir = ecosystem_path / "skills-box"
    config_file = ecosystem_path / "config" / "main.yaml"
    bootstrap_file = bootstrap_dir / "using-yukta.yaml"
    index_file = skills_box_dir / "index.yaml"
    agents_dir = ecosystem_path / "agents"
    skills_dir = ecosystem_path / "skills"
    tools_dir = ecosystem_path / "tools"
    teams_dir = ecosystem_path / "teams"

    if not config_file.exists():
        errors.append("config/main.yaml not found")
    else:
        errors.extend(validate_config(config_file))

    if not bootstrap_file.exists():
        errors.append("bootstrap/using-yukta.yaml not found")
    else:
        errors.extend(validate_bootstrap(bootstrap_file))

    if not index_file.exists():
        errors.append("skills-box/index.yaml not found")
    else:
        errors.extend(validate_index(index_file))

    if not agents_dir.exists():
        errors.append("agents/ directory not found")
    elif not list(agents_dir.glob("*.yaml")):
        errors.append("No agent YAML files in agents/")
    if not skills_dir.exists():
        errors.append("skills/ directory not found")

    if not tools_dir.exists():
        errors.append("tools/ directory not found")
    elif not list(tools_dir.glob("*.yaml")):
        errors.append("No tool YAML files in tools/")

    teams_dir = ecosystem_path / "teams"
    if not teams_dir.exists():
        errors.append("teams/ directory not found")
    
    if errors:
        click.echo("\nValidation errors found:", err=True)
        for error in errors:
            click.echo(f"  - {error}", err=True)
        sys.exit(1)

    known_skill_ids = {skill_dir.name for skill_dir in skills_dir.iterdir() if skill_dir.is_dir()}
    known_tool_ids = set()
    known_agent_ids = set()

    for tool_file in tools_dir.glob("*.yaml"):
        try:
            tool_data = yaml.safe_load(tool_file.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        if isinstance(tool_data, dict) and tool_data.get("tool_id"):
            known_tool_ids.add(tool_data["tool_id"])

    for agent_file in agents_dir.glob("*.yaml"):
        try:
            agent_data = yaml.safe_load(agent_file.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        if isinstance(agent_data, dict) and agent_data.get("agent_id"):
            known_agent_ids.add(agent_data["agent_id"])

    for skill_dir in skills_dir.iterdir() if skills_dir.exists() else []:
        if skill_dir.is_dir():
            errors.extend(validate_skill(skill_dir))

    for tool_file in tools_dir.glob("*.yaml"):
        errors.extend(validate_tool(tool_file))

    for agent_file in agents_dir.glob("*.yaml"):
        errors.extend(validate_agent(agent_file, known_skill_ids, known_tool_ids))

    for team_file in teams_dir.glob("*.yaml") if teams_dir.exists() else []:
        errors.extend(validate_team(team_file, known_agent_ids))

    if errors:
        click.echo("\nValidation errors found:", err=True)
        for error in errors:
            click.echo(f"  - {error}", err=True)
        sys.exit(1)
    
    # Generate skills-box index
    click.echo("Generating skills-box index...")
    generate_index(ecosystem_path)

    # Compile ecosystem
    click.echo("Compiling ecosystem to build/ecosystem.yaml...")
    compile_ecosystem(ecosystem_path)

    click.echo("\nValidation successful!")
    click.echo(f"Compiled file: {ecosystem_path / 'build' / 'ecosystem.yaml'}")
    click.echo("You can now use this ecosystem with load_agent().")


@cli.group()
def tool():
    """Tool execution commands"""
    pass


@tool.command("run")
@click.argument("tool_name")
@click.option("--path", "-p", default=".", help="Path to ecosystem directory")
@click.option("--param", "-P", multiple=True, help="Parameters as KEY=VALUE")
def tool_run(tool_name, path, param):
    """Run a tool from the ecosystem"""
    ecosystem_path = Path(path)
    
    if not ecosystem_path.exists():
        click.echo(f"Error: Path '{path}' does not exist", err=True)
        sys.exit(1)
    
    params = {}
    for p in param:
        if "=" in p:
            key, value = p.split("=", 1)
            params[key] = value
        else:
            click.echo(f"Warning: Invalid parameter '{p}', skipping", err=True)
    
    try:
        result = run_tool(tool_name, ecosystem_path, params)
        click.echo(result)
    except Exception as e:
        click.echo(f"Error running tool: {e}", err=True)
        sys.exit(1)


def main():
    """Entry point for CLI"""
    cli()


if __name__ == "__main__":
    main()